version: '3.8'
services:
  postgresdb:
      container_name: postgresdb
      build:
          context: ./postgresql
          dockerfile: Dockerfile
      restart: always
      environment:
          POSTGRES_DB: POSTGRES_DB
          POSTGRES_USER: POSTGRES_USER
          POSTGRES_PASSWORD: POSTGRES_PASSWORD
      volumes:
        - ./postgresql/pgdata:/var/lib/postgresql/data
      ports:
        - "5433:5432"
  php-apache-environment:
    container_name: php-apache
    build:
        context: ./php
        dockerfile: Dockerfile
    depends_on:
        - postgresdb
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - "8000:80"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8081:80"
    depends_on:
      - postgresdb